[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_mint = "HmxB2ZgcuM35MhP7JELUX6yQtcCbEkiMHTL83QU58uLP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
